name: Auto‑Generate requirements.txt
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'  # enables dependency caching :contentReference[oaicite:1]{index=1}

      - name: Generate requirements.txt via pipreqs-action
        uses: ryan-rozario/pipreqs-action@v3.0.0
        with:
          PROJECT_PATH: '.'                   # path containing your .py files
          REQUIREMENT_PATH: './requirements.txt'
          # PROJECT_NAME: 'MyProject'        # optional commit message context :contentReference[oaicite:2]{index=2}

      - name: Commit and push requirements.txt
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@users.noreply.github.com"
          git add requirements.txt
          git diff --quiet && echo "No changes in requirements.txt" || git commit -m "Auto‑update requirements.txt"
          git push
